spring:
  profiles:
    active: test
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8090
  servlet:
    context-path: /master

mybatis:
  # type aliases
  typeAliasesPackage: com.mathbeta.microedge.entity
  mapperLocations: classpath:mapper/*.xml
  configLocation: classpath:mybatis-config.xml

---

# dev profile
spring:
  profiles: test

  datasource:
    # url: jdbc:h2:mem:springboot;MODE=MYSQL;DB_CLOSE_DELAY=-1
    url: jdbc:mysql://127.0.0.1:3306/microedge?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    # driver-class-name: org.h2.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

logging:
  level:
    com.mathbeta.microedge.mapper: debug